
/*
 * Clase encarga de crear nuestro panel de control
 */

/*
 * Panel.java
 *
 * Created on 05-ene-2012, 12:16:24
 */
/**
 *
 * @author Richy
 */
public class Panel extends javax.swing.JFrame {

    public static Thread[] hilo1 = new Thread[50];

    /**
     * Creates new form Panel
     */
    public Panel() {
        setTitle("Panel de Control - Proyecto Zaragoza");
        setLocationRelativeTo(null);
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numcochesarriba_etiqueta = new javax.swing.JLabel();
        coches_total = new javax.swing.JLabel();
        boton_atasco_arriba = new javax.swing.JButton();
        numcochesabajo_etiqueta = new javax.swing.JLabel();
        coches_arriba = new javax.swing.JLabel();
        coches_abajo = new javax.swing.JLabel();
        coches_totales_etiqueta = new javax.swing.JLabel();
        boton_atasco_abajo = new javax.swing.JButton();
        boton_trafico_normal_arriba = new javax.swing.JButton();
        trafico_normal_abajo = new javax.swing.JButton();
        boton_resetear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numcochesarriba_etiqueta.setText("Número coches arriba");

        coches_total.setText("jLabel1");

        boton_atasco_arriba.setText("Atasco arriba");
        boton_atasco_arriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_atasco_arribaActionPerformed(evt);
            }
        });

        numcochesabajo_etiqueta.setText("Número coches abajo");

        coches_arriba.setText("jLabel2");

        coches_abajo.setText("jLabel1");

        coches_totales_etiqueta.setText("Coches totales:");

        boton_atasco_abajo.setText("Atasco abajo");
        boton_atasco_abajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_atasco_abajoActionPerformed(evt);
            }
        });

        boton_trafico_normal_arriba.setText("Tráfico normal arriba");
        boton_trafico_normal_arriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_trafico_normal_arribaActionPerformed(evt);
            }
        });

        trafico_normal_abajo.setText("Tráfico normal abajo");
        trafico_normal_abajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trafico_normal_abajoActionPerformed(evt);
            }
        });

        boton_resetear.setText("Resetear");
        boton_resetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_resetearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(boton_atasco_arriba)
                        .addGap(18, 18, 18)
                        .addComponent(boton_atasco_abajo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trafico_normal_abajo)
                            .addComponent(boton_trafico_normal_arriba)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numcochesarriba_etiqueta)
                                .addGap(18, 18, 18)
                                .addComponent(coches_arriba))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numcochesabajo_etiqueta)
                                    .addComponent(coches_totales_etiqueta))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coches_total)
                                    .addComponent(coches_abajo)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(boton_resetear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numcochesarriba_etiqueta)
                    .addComponent(coches_arriba))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numcochesabajo_etiqueta)
                    .addComponent(coches_abajo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coches_totales_etiqueta)
                    .addComponent(coches_total))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_atasco_arriba)
                    .addComponent(boton_atasco_abajo))
                .addGap(18, 18, 18)
                .addComponent(boton_trafico_normal_arriba)
                .addGap(18, 18, 18)
                .addComponent(trafico_normal_abajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_resetear))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_atasco_arribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_atasco_arribaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_boton_atasco_arribaActionPerformed

    private void boton_atasco_abajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_atasco_abajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_atasco_abajoActionPerformed

    private void boton_trafico_normal_arribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_trafico_normal_arribaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_trafico_normal_arribaActionPerformed

    private void trafico_normal_abajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trafico_normal_abajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trafico_normal_abajoActionPerformed

    private void boton_resetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_resetearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_resetearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_atasco_abajo;
    private javax.swing.JButton boton_atasco_arriba;
    private javax.swing.JButton boton_resetear;
    private javax.swing.JButton boton_trafico_normal_arriba;
    private javax.swing.JLabel coches_abajo;
    private javax.swing.JLabel coches_arriba;
    private javax.swing.JLabel coches_total;
    private javax.swing.JLabel coches_totales_etiqueta;
    private javax.swing.JLabel numcochesabajo_etiqueta;
    private javax.swing.JLabel numcochesarriba_etiqueta;
    private javax.swing.JButton trafico_normal_abajo;
    // End of variables declaration//GEN-END:variables
}
